/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.scene {
    export class MainSceneUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scene/MainScene");
        }
    }
    REG("ui.scene.MainSceneUI",MainSceneUI);
}
export module ui.view {
    export class LoadingUI extends Laya.View {
		public tank:Laya.Clip;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Clip","props":{"var":"tank","skin":"Characters/Tank_8.png","index":4,"clipY":4,"clipX":4,"centerY":0,"centerX":0},"compId":3}],"loadList":["Characters/Tank_8.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.view.LoadingUI",LoadingUI);
}