/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.scene {
    export class MainSceneUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scene/MainScene");
        }
    }
    REG("ui.scene.MainSceneUI",MainSceneUI);
}
export module ui.view {
    export class BaseTestUI extends Laya.View {
		public tank:Laya.Clip;
		public closeBtn:Laya.Button;
		public dialogBtn:Laya.Button;
		public loadingBtn:Laya.Button;
		public viewBtn:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"top":0,"skin":"comp/image.png","right":0,"left":0,"bottom":0},"compId":8},{"type":"Clip","props":{"y":0,"x":0,"var":"tank","skin":"Characters/Tank_8.png","index":4,"clipY":4,"clipX":4,"centerY":-1,"centerX":0},"compId":3},{"type":"Button","props":{"y":327,"x":282,"var":"closeBtn","skin":"comp/button.png","label":"close"},"compId":4},{"type":"Button","props":{"y":252,"x":472,"var":"dialogBtn","skin":"comp/button.png","label":"dialog"},"compId":5},{"type":"Button","props":{"y":304,"x":472,"var":"loadingBtn","skin":"comp/button.png","label":"base"},"compId":6},{"type":"Button","props":{"y":362,"x":472,"var":"viewBtn","skin":"comp/button.png","label":"view"},"compId":7}],"loadList":["comp/image.png","Characters/Tank_8.png","comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(BaseTestUI.uiView);
        }
    }
    REG("ui.view.BaseTestUI",BaseTestUI);
    export class DialogTestUI extends Laya.View {
		public box:Laya.Box;
		public tank:Laya.Clip;
		public closeBtn:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Image","props":{"top":0,"skin":"Characters/Tank_2.png","right":0,"left":0,"bottom":0},"compId":8},{"type":"Box","props":{"width":200,"var":"box","height":200,"centerY":0,"centerX":0},"compId":9,"child":[{"type":"Image","props":{"top":0,"skin":"comp/image.png","sizeGrid":"0,0,0,0","right":0,"left":0,"bottom":0},"compId":10},{"type":"Clip","props":{"y":550,"x":303,"var":"tank","skin":"Characters/Tank_7.png","index":4,"clipY":4,"clipX":4,"centerY":-1,"centerX":0},"compId":3},{"type":"Button","props":{"y":39,"x":62.5,"var":"closeBtn","skin":"comp/button.png","label":"close"},"compId":4}]}],"loadList":["Characters/Tank_2.png","comp/image.png","Characters/Tank_7.png","comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(DialogTestUI.uiView);
        }
    }
    REG("ui.view.DialogTestUI",DialogTestUI);
    export class LoadingUI extends Laya.View {
		public tank:Laya.Clip;
		public btn_close:Laya.Button;
		public btn_connect:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Image","props":{"top":0,"skin":"Characters/Tank_7.png","right":0,"left":0,"bottom":0},"compId":17},{"type":"Clip","props":{"var":"tank","skin":"Characters/Tank_4.png","index":4,"clipY":4,"clipX":4,"centerY":-1,"centerX":0},"compId":3},{"type":"Button","props":{"y":327,"x":282.5,"var":"btn_close","skin":"comp/button.png","label":"close"},"compId":4},{"type":"Button","props":{"y":222,"x":282.5,"var":"btn_connect","skin":"comp/button.png","label":"connect"},"compId":5}],"loadList":["Characters/Tank_7.png","Characters/Tank_4.png","comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.view.LoadingUI",LoadingUI);
    export class ViewTestUI extends Laya.View {
		public tank:Laya.Clip;
		public closeBtn:Laya.Button;
		public viewBtn:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"top":0,"skin":"comp/image.png","right":0,"left":0,"bottom":0},"compId":7},{"type":"Clip","props":{"y":0,"x":0,"var":"tank","skin":"Characters/$狼.png","index":4,"clipY":4,"clipX":4,"centerY":-1,"centerX":0},"compId":3},{"type":"Button","props":{"y":327,"x":282,"var":"closeBtn","skin":"comp/button.png","label":"close"},"compId":4},{"type":"Button","props":{"y":385,"x":282.5,"var":"viewBtn","skin":"comp/button.png","label":"view"},"compId":5}],"loadList":["comp/image.png","Characters/$狼.png","comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(ViewTestUI.uiView);
        }
    }
    REG("ui.view.ViewTestUI",ViewTestUI);
    export class ViewTest1UI extends Laya.View {
		public tank:Laya.Clip;
		public closeBtn:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"top":0,"skin":"comp/image.png","right":0,"left":0,"bottom":0},"compId":6},{"type":"Clip","props":{"y":0,"x":0,"var":"tank","skin":"Characters/$狼.png","index":4,"clipY":4,"clipX":4,"centerY":-1,"centerX":0},"compId":3},{"type":"Button","props":{"y":327,"x":282,"var":"closeBtn","skin":"comp/button.png","label":"close"},"compId":4}],"loadList":["comp/image.png","Characters/$狼.png","comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(ViewTest1UI.uiView);
        }
    }
    REG("ui.view.ViewTest1UI",ViewTest1UI);
}