/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.scene {
    export class MainSceneUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scene/MainScene");
        }
    }
    REG("ui.scene.MainSceneUI",MainSceneUI);
}
export module ui.view {
    export class LoadingUI extends Laya.View {
		public tank:Laya.Clip;
		public btn_close:Laya.Button;
		public btn_connect:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":640,"height":1136},"compId":2,"child":[{"type":"Clip","props":{"var":"tank","skin":"Characters/Tank_4.png","index":4,"clipY":4,"clipX":4,"centerY":-1,"centerX":0},"compId":3},{"type":"Button","props":{"y":337,"x":282.5,"var":"btn_close","skin":"comp/button.png","label":"close"},"compId":4},{"type":"Button","props":{"y":231,"x":282.5,"var":"btn_connect","skin":"comp/button.png","label":"connect"},"compId":5}],"loadList":["Characters/Tank_4.png","comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.view.LoadingUI",LoadingUI);
}