/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainScene from "./scene/MainScene"
import Test from "./game/ui/view/APage/Test"
import HLabel from "./core/game/script/HLabel"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="scene/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scene/MainScene.ts",MainScene);
        reg("game/ui/view/APage/Test.ts",Test);
        reg("core/game/script/HLabel.ts",HLabel);
    }
}
GameConfig.init();